# -*- coding: utf-8 -*-
"""day2 lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0cRcMUV7bRDHsmQgCFH1AEvMO7ZZryZ
"""

# 1. Pass or Fail
marks = int(input("Enter marks: "))

if marks >= 35:
    print("Pass")
else:
    print("Fail")

# 2. Voting Eligibility
age = int(input("Enter age: "))

if age >= 18:
    print("Eligible to Vote")
else:
    print("Not Eligible to Vote")

# 3. Shopping Discount
bill = float(input("Enter shopping bill: "))

if bill > 5000:
    discount = bill * 0.10
else:
    discount = 0

final_amount = bill - discount
print("Discount:", discount)
print("Final Amount:", final_amount)

# 4. Password Verification
stored_password = "python123"
password = input("Enter password: ")

if password == stored_password:
    print("Access Granted")
else:
    print("Wrong Password")

# 5. Grade Assignment
marks = int(input("Enter marks: "))

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

# 6. Simple Calculator
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

choice = int(input("Enter choice: "))

if choice == 1:
    print("Result =", num1 + num2)
elif choice == 2:
    print("Result =", num1 - num2)
elif choice == 3:
    print("Result =", num1 * num2)
elif choice == 4:
    if num2 != 0:
        print("Result =", num1 / num2)
    else:
        print("Division by zero not allowed")
else:
    print("Invalid Choice")

# 7. Electricity Bill
units = int(input("Enter units consumed: "))

if units <= 100:
    bill = units * 2
elif units <= 200:
    bill = units * 3
else:
    bill = units * 5

print("Electricity Bill =", bill)

# 8. Ticket Fare
age = int(input("Enter age: "))

if age < 5:
    fare = 0
elif age <= 12:
    fare = 50
else:
    fare = 100

print("Ticket Fare =", fare)

# 9. Loan Approval
salary = int(input("Enter salary: "))

if salary > 30000:
    credit = int(input("Enter credit score: "))
    if credit > 700:
        print("Loan Approved")
    else:
        print("Loan Rejected - Low Credit Score")
else:
    print("Loan Rejected - Salary Too Low")

# 10. College Admission
academic = float(input("Enter academic percentage: "))

if academic > 60:
    entrance = int(input("Enter entrance exam score: "))
    if entrance > 70:
        print("Admission Eligible")
    else:
        print("Not Eligible - Entrance Score Low")
else:
    print("Not Eligible - Academic Marks Low")

# 11. Company Recruitment
degree = float(input("Enter degree percentage: "))

if degree > 65:
    aptitude = int(input("Enter aptitude score: "))
    if aptitude > 75:
        print("Selected")
    else:
        print("Rejected - Aptitude Score Low")
else:
    print("Rejected - Degree Percentage Low")

# 12. Scholarship
marks = float(input("Enter percentage: "))

if marks > 80:
    attendance = float(input("Enter attendance percentage: "))
    if attendance > 75:
        print("Scholarship Awarded")
    else:
        print("Scholarship Not Awarded - Attendance Low")
else:
    print("Scholarship Not Awarded - Marks Low")

# 13. ATM Withdrawal
balance = float(input("Enter account balance: "))
amount = float(input("Enter withdrawal amount: "))

if balance >= amount:
    pin = input("Enter PIN: ")
    if pin == "1234":
        print("Withdrawal Successful")
    else:
        print("Incorrect PIN")
else:
    print("Insufficient Balance")

# 14. Secure Login
username = input("Enter username: ")

if username == "admin":
    password = input("Enter password: ")
    if password == "admin123":
        otp = input("Enter OTP: ")
        if otp == "5678":
            print("Login Successful")
        else:
            print("Invalid OTP")
    else:
        print("Wrong Password")
else:
    print("Invalid Username")

# 15. Hospital Appointment
doctor = input("Is doctor available? (yes/no): ")

if doctor.lower() == "yes":
    slots = int(input("Enter available slots: "))
    if slots > 0:
        print("Appointment Confirmed")
    else:
        print("No Slots Available")
else:
    print("Doctor Not Available")

# 16. Cybersecurity Lab Access
registered = input("Registered? (yes/no): ")

if registered.lower() == "yes":
    fees = input("Fees Paid? (yes/no): ")
    if fees.lower() == "yes":
        print("Access Granted")
    else:
        print("Please Pay Fees")
else:
    print("Registration Required")

# 17. Employee Bonus
experience = int(input("Enter years of experience: "))

if experience > 3:
    rating = float(input("Enter performance rating: "))
    if rating >= 8:
        print("Bonus Eligible")
    else:
        print("Bonus Not Eligible")
else:
    print("Not Eligible for Bonus")

# 18. Online Examination Portal
hall_ticket = input("Hall Ticket Available? (yes/no): ")

if hall_ticket.lower() == "yes":
    fees = input("Fees Cleared? (yes/no): ")
    if fees.lower() == "yes":
        print("Exam Access Granted")
    else:
        print("Fees Pending")
else:
    print("Hall Ticket Not Available")

# 19. Hostel Room Allotment
selected = input("Selected for Admission? (yes/no): ")

if selected.lower() == "yes":
    rooms = int(input("Available Rooms: "))
    if rooms > 0:
        print("Room Allotted")
    else:
        print("No Rooms Available")
else:
    print("Admission Not Confirmed")

# 20. Online Shopping Discount
member = input("Premium Member? (yes/no): ")
amount = float(input("Enter Purchase Amount: "))

if member.lower() == "yes":
    if amount > 5000:
        discount = amount * 0.20
    else:
        discount = 0
else:
    if amount > 5000:
        discount = amount * 0.10
    else:
        discount = 0

print("Discount =", discount)
print("Final Amount =", amount - discount)