# -*- coding: utf-8 -*-
"""day 4 lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9qbxd1Z0PrkhnSDPg8IQ5fa6EeKVdg7
"""

#Print numbers from 1 to 10
i = 1
while i <= 10:
    print(i)
    i += 1

# Print numbers from 10 to 1
i = 10
while i >= 1:
    print(i)
    i -= 1

# Print all even numbers from 1 to 20
i = 2
while i <= 20:
    print(i)
    i += 2

# Print all odd numbers from 1 to 20
i = 1
while i <= 20:
    print(i)
    i += 2

#Find the sum of numbers from 1 to 50
i = 1
sum = 0

while i <= 50:
    sum += i
    i += 1

print("Sum =", sum)

#Print the multiplication table of a given number
num = int(input("Enter a number: "))
i = 1

while i <= 10:
    print(num, "x", i, "=", num * i)
    i += 1

# Count the number of digits in a number
num = int(input("Enter a number: "))
count = 0

while num > 0:
    count += 1
    num //= 10

print("Digits =", count)

#Reverse a given number
num = int(input("Enter a number: "))
reverse = 0

while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num //= 10

print("Reverse =", reverse)

#Find the sum of digits of a number
num = int(input("Enter a number: "))
sum = 0

while num > 0:
    digit = num % 10
    sum += digit
    num //= 10

print("Sum of digits =", sum)

#Find the product of digits of a number
num = int(input("Enter a number: "))
product = 1

while num > 0:
    digit = num % 10
    product *= digit
    num //= 10

print("Product =", product)

#Print the Fibonacci series up to n terms
n = int(input("Enter number of terms: "))

a = 0
b = 1
count = 1

while count <= n:
    print(a, end=" ")
    c = a + b
    a = b
    b = c
    count += 1

#Calculate the factorial of a number using a while loop
num = int(input("Enter a number: "))
fact = 1

while num > 0:
    fact *= num
    num -= 1

print("Factorial =", fact)

#Find the largest digit in a number
num = int(input("Enter a number: "))
largest = 0

while num > 0:
    digit = num % 10
    if digit > largest:
        largest = digit
    num //= 10

print("Largest digit =", largest)

#Find the smallest digit in a number
num = int(input("Enter a number: "))
smallest = 9

while num > 0:
    digit = num % 10
    if digit < smallest:
        smallest = digit
    num //= 10

print("Smallest digit =", smallest)

#Check whether a number is an Armstrong Number
num = int(input("Enter a number: "))
original = num
digits = len(str(num))
sum = 0

while num > 0:
    digit = num % 10
    sum += digit ** digits
    num //= 10

if sum == original:
    print("Armstrong Number")
else:
    print("Not an Armstrong Number")

# check whether a number is a palindrome
num = int(input("Enter a number: "))
original = num
reverse = 0

while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num //= 10

if original == reverse:
    print("Palindrome")
else:
    print("Not Palindrome")

#Check whether a number is a Spy Number
num = int(input("Enter a number: "))
sum = 0
product = 1
total=num
while total > 0:
    digit = total % 10
    sum += digit
    product *= digit
    total //= 10

if sum == product:
    print(num, "is a Spy Number")
else:
    print(num, "is not a Spy Number")