# -*- coding: utf-8 -*-
"""day 4 lab task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WjlZlEdWrGJEtOMBwUhWc5zb6AyM6Uy
"""

#Print numbers from 1 to 100 and stop at 50
i = 1

while i <= 100:
    print(i)
    if i == 50:
        break
    i += 1

#Ask for a password until the correct password is entered
correct_password = "python123"

while True:
    password = input("Enter Password: ")

    if password == correct_password:
        print("Access Granted")
        break
    else:
        print("Wrong Password! Try Again.")

#Search for a name in a list and stop when found
names = ["arun", "bala", "divya", "kavi", "meena"]

search = input("Enter name to search: ")

for name in names:
    if name == search:
        print("Name Found")
        break
else:
    print("Name Not Found")

#Print numbers from 1 to 20, skipping multiples of 3
i = 1

while i <= 20:
    if i % 3 == 0:
        i+=1
        continue

    print(i)
    i += 1

#Print only odd numbers from 1 to 50
i = 1

while i <= 50:
    if i % 2 == 0:
        i += 1
        continue

    print(i)
    i += 1

#Skip vowels while printing a string
text = input("Enter a string: ")

for ch in text:
    if ch.lower() in "aeiou":
        continue
    print(ch, end="")

#Create an empty function using pass
def my_function():
    pass

print("Function Created")

#create an empty class using pass
class Student:
    pass

print("Class Created")

#Create a loop where a condition is not implemented yet and use pass
for i in range(1, 11):
    if i == 5:
        pass
    else:
        print(i)