# -*- coding: utf-8 -*-
"""day 5 lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZevhIxEznY4x300wRhNsk86TWrj2A3w
"""

# Task 1: Username Formatter

username = input("Enter username: ")
print("Uppercase :", username.upper())
print("Lowercase :", username.lower())
print("Title Case:", username.title())

# Task 2: Email Validator
email = input("Enter email: ")
print("Starts with a letter:", email[0].isalpha())
print("Ends with .com:", email.endswith(".com"))

# Task 3: Character Counter
sentence = input("Enter a sentence: ")
print("Count of 'a':", sentence.count('a'))
print("Count of 'e':", sentence.count('e'))

# Task 4: Search a Character
word = input("Enter a word: ")
ch = input("Enter character to search: ")
position = word.find(ch)
if position != -1:
    print("Character found at position:", position)
else:
    print("Character Not Found")

# Task 5: Password Checker
password = input("Enter password: ")
print("Only Alphabets :", password.isalpha())
print("Only Digits    :", password.isdigit())
print("Alphanumeric   :", password.isalnum())

# Task 6: Name Decoration
name = input("Enter your name: ")
print("Centered      :", name.center(20, '*'))
print("Left Justified:", name.ljust(20, '-'))
print("Right Justified:", name.rjust(20, '-'))

# Task 7: Text Converter
sentence = input("Enter a sentence: ")
print("Uppercase :", sentence.upper())
print("Lowercase :", sentence.lower())
print("Swap Case :", sentence.swapcase())

# Task 8: Replace Words
sentence = input("Enter a sentence: ")
new_sentence = sentence.replace("Python", "Java")
print("Modified Sentence:", new_sentence)

# Task 9: Roll Number Formatter
roll = input("Enter roll number: ")
print("Formatted Roll Number:", roll.zfill(10))

# Task 10: Case Analyzer
word = input("Enter a word: ")
print("All Uppercase:", word.isupper())
print("All Lowercase:", word.islower())
print("Title Case   :", word.istitle())