# -*- coding: utf-8 -*-
"""day 3 lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYZkQJ69GuGvmpHku72nG34GenD8MvSf
"""

#Print your name 5 times using a for loop
for i in range(5):
    print("Abinaya")

#Print numbers from 1 to 20
for i in range(1, 21):
    print(i)

#print numbers from 20 to 1
for i in range(20, 0, -1):
    print(i)

#print all even numbers from 1 to 50
for i in range(2, 51, 2):
    print(i)

#print all odd numbers from 1 to 50
for i in range(1, 51, 2):
    print(i)

#sum of numbers from 1 to 10
total = 0

for i in range(1, 11):
    total += i
print("Sum =", total)

#Print the multiplication table of a number entered by the user
num = int(input("Enter a number: "))

for i in range(1, 11):
    print(num, "x", i, "=", num * i)

#Count how many letters are in your name
name = input("Enter your name: ")
count = 0
for letter in name:
    count += 1

print("Number of letters:", count)

#Print each character of a word on a new line
word = input("Enter a word: ")
for ch in word:
    print(ch)

#Count the number of vowels in a word
word = input("Enter a word: ")
count = 0
for ch in word.lower():
    if ch in "aeiou":
        count += 1
print("Number of vowels:", count)

#Print the Cross pattern
n = 5
for i in range(n):
    for j in range(n):
        if i == j or i + j == n - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

#Print the right angle traingle
n = 5
for i in range(1, n + 1):
    for j in range(i):
        print("*", end=" ")
    print()