# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMggUVYJR94jlQd-tqM_sqI8kPAHY49L
"""

# 1. List Methods
numbers = [10,20,30,40,50,60,70,80,90,100]
numbers.append(110)
numbers.insert(3, 35)
numbers.remove(50)
numbers.pop()
numbers.extend([120,130])
print(numbers)

# 2. Count occurrences
numbers = [10,20,30,20,40,20]
num = int(input("Enter number: "))
print(numbers.count(num))

# 3. Find index
numbers = [10,20,30,40,50]
num = int(input("Enter number: "))
print(numbers.index(num))

# 4. Reverse a list
numbers = [10,20,30,40,50]
numbers.reverse()
print(numbers)

# 5. Sort ascending and descending
numbers = [50,10,30,20,40]
numbers.sort()
print("Ascending:", numbers)
numbers.sort(reverse=True)
print("Descending:", numbers)

# 6. Clear list
numbers = [1,2,3,4,5]
numbers.clear()
print(numbers)

# 7. Copy list
list1 = [10,20,30]
list2 = list1.copy()
print(list2)