# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_yRu0AWo1h6XpTGkyckI7IMow3HcdU9
"""

#Print numbers from 1 to 10 using for loop
for i in range(1, 11):
    print(i)

#Multiplication table of a number
num = int(input("Enter a number: "))
for i in range(1, 11):
    print(num, "x", i, "=", num * i)

#Print all even numbers from 1 to 50
for i in range(1, 51):
    if i % 2 == 0:
        print(i)

#Factorial of a number
num = int(input("Enter a number: "))
fact = 1
for i in range(1, num + 1):
    fact = fact * i
print("Factorial =", fact)

#Check whether a number is palindrome using while loop
num = int(input("Enter a number: "))
temp = num
reverse = 0
while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num = num // 10
if temp == reverse:
    print("Palindrome")
else:
    print("Not Palindrome")

#Print the pattern
for i in range(1, 5):
    print("*" * i)

#Print even numbers from 2 to 20
for i in range(2, 21, 2):
    print(i)

#Print numbers from 1 to 10 using while loop
i = 1
while i <= 10:
    print(i)
    i += 1

#Print numbers from 1 to 20 using while loop
i = 1
while i <= 20:
    print(i)
    i += 1

#Print numbers in reverse from 50 to 1 using for loop
for i in range(50, 0, -1):
    print(i)

#Use a for loop to enter a number between 1 and 100
num = int(input("Enter a number between 1 and 100: "))
for i in range(1, num + 1):
    print(i)

#Skip printing if the number is divisible by 3 using continue
for i in range(1, 21):
    if i % 3 == 0:
        continue
    print(i)

#Stop the loop if the number is divisible by 9 using break
for i in range(1, 21):
    if i % 9 == 0:
        print(i)
        break
    print(i)

#Use a while loop to count down from the user's number to 1
num = int(input("Enter a number: "))
while num >= 1:
    print(num)
    num -= 1

#Use pass when the number is exactly 5
num = 10
while num >= 1:
    if num == 5:
        pass
    else:
        print(num)
    num -= 1

#Stop when the number is less than 1
num = 5
while True:
    if num < 1:
        break
    print(num)
    num -= 1

#Using a for loop, print each letter in the word "PYTHON" except "H"
word = "PYTHON"
for ch in word:
    if ch == "H":
        continue
    print(ch)

#Skip number 17 using continue
num = 20
while num >= 1:
    if num == 17:
        num -= 1
        continue
    print(num)
    num -= 1

#Break at number 13
num = 20
while num >= 1:
    if num == 13:
        break
    print(num)
    num -= 1