# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVs4x_7uHNiqrui1YUmOBW_9yjsheNiy
"""

#task1
name=input("enter name: ")
print(name.upper())

#task2
sentence = input("Enter a sentence: ")
print(sentence.lower())

#task3
sentence = input("Enter a sentence: ")
print(sentence.capitalize())

#task4
name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("My name is {} and I am {} years old.".format(name, age))

#task5
word = input("Enter a word: ")
ch = input("Enter a character: ")
print(word.index(ch))

#task6
sentence = input("Enter a sentence: ")
sub = input("Enter a substring: ")
print(sentence.find(sub))

#task7
word = input("Enter a word: ")
print(word.endswith("ing"))

#task8
text = "Name\tAge\tCity"
print(text)
print(text.expandtabs(10))

# 9. Encode a string into UTF-8
text = input("Enter a string: ")
print(text.encode("utf-8"))

# 10. Check if a string contains only digits.
text = input("Enter a string: ")
print(text.isdigit())

# 11. Check if a string is numeric.
text = input("Enter a string: ")
print(text.isnumeric())

# 12. Check if a string is alphanumeric.
text = input("Enter a string: ")
print(text.isalnum())

# 13. Check if a string contains only ASCII characters.
text = input("Enter a string: ")
print(text.isascii())

# 14. Check if a string contains only alphabets.
text = input("Enter a string: ")
print(text.isalpha())