# -*- coding: utf-8 -*-
"""tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfSWPkge2spndrCT0FNZjVFJEGTFWFzb
"""

# Length, Maximum and Minimum
t = (10,20,30,40,50)
print("Length:", len(t))
print("Maximum:", max(t))
print("Minimum:", min(t))

# Count an element
t = (10,20,30,20,40,20)
print(t.count(20))

# Find index
t = (10,20,30,40,50)
print(t.index(30))

# Convert tuple → list → tuple
t = (10,20,30)
l = list(t)
print(l)
l.append(50)
t = tuple(l)
print(t)

# Concatenate two tuples
t1 = (1,2,3)
t2 = (4,5,6)
t3 = t1 + t2
print(t3)

# Slice tuple (index 2 to 5)
t=(10,20,30,40,50,60,70,80)
print(t[2:6])

# Check whether an element exists in a tuple
t = (10,20,30,40,50)
num = int(input("Enter element: "))
if num in t:
    print("Element Found")
else:
    print("Element Not Found")